### ISSUE TITLE
Bring back admin bar

### ISSUE THREAD

**Issue by timiwahalahti** [digitoimistodude/air-helper#13]
Admin bar is really usable when editing the site. Benefits of it overrule the small design implications that the admin bar has. Thus bring back admin bar, but remove all un-necessary things from it.

**Comment by ronilaukkarinen** [comment]
I would also suggest making it more minimal style-wise, less intrusive. The white style we had previously was not good looking. Will try to improve this.

**Comment by timiwahalahti** [comment]
Fixed in 6c18e26333dc72dbf511e9f9725960f54e8b9863
