### ISSUE TITLE
Maybe disable some views by default

### ISSUE THREAD

**Issue by timiwahalahti** [digitoimistodude/air-helper#3]
In most of our projects, there's really no need for most of the default archive views that WordPress haves. Sometimes in hurry, those might end up being forgotten and looking really bad (unstyled).

I'm considering disabling search view, tag, category, author and date archives by default. Every view could be de-disabled via hook in theme or plugin. In the name of backward compatibility, if added to plugin, we need to check if plugin version is earlier than X and do de-disable automatically. 

Opinions @ronilaukkarinen and @artotoivanen?

**Comment by ronilaukkarinen** [comment]
Sounds good to me.

**Comment by artotoivanen** [comment]
Maybe that would complicate things unnecessarily. I prefer to disable archive for date and authors through Yoast SEO plugin. To disable search I would use a ready made plugin.

**Comment by timiwahalahti** [comment]
Introduced this functionality in commit [c1f1aa0](https://github.com/digitoimistodude/air-helper/commit/c1f1aa092718254a726eb1ca951aeef5ba02d272). For old installations, there is check not to deactivate views. Only new installations should be affected.

Turn off by using `remove_action( 'template_redirect', 'air_helper_disable_views' )` or spesific views, for example tag archive, with `add_filter( 'air_helper_disable_views_tag', '__return_false' )`
