### ISSUE TITLE
ACF Key does not populate to settings from .env

### ISSUE THREAD

**Issue by ronilaukkarinen** [digitoimistodude/air-helper#37]
From time to time I see settings page license field empty and updates are failing because of this:

![Screen-Shot-2021-05-24-11-33-50](https://user-images.githubusercontent.com/1534150/119321316-302f2380-bc85-11eb-9b57-3164920b5938.png)

**Comment by timiwahalahti** [comment]
Fixed with workaround on 8c83e5a9996ce93ca9f824bcd932a8a7e7b996e2, will be included in 2.11 release.
