### ISSUE TITLE
Warning when overriding Hide ACF for all users with user meta

### ISSUE THREAD

**Issue by villekujansuu** [digitoimistodude/air-helper#54]
Thought I should let you know that I get this warning when overriding this with user meta and the override wont work:
> ( ! ) Warning: Undefined variable $menu_links in \content\plugins\air-helper\inc\admin\acf.php on line 28

Adding `$menu_links` in `function air_helper_maybe_hide_acf()` or changing this `if ( 'true' === $meta_override ) { return $menu_links; }`  to this `if ( 'true' === $meta_override ) { return true  }` fixes it.

**Comment by ronilaukkarinen** [comment]
@villekujansuu Thanks! While you're at it, can you send a PR we can review and approve?

**Comment by villekujansuu** [comment]
@ronilaukkarinen No problem. I sent a PR,
