### ISSUE TITLE
Add settings view for Polylang strings when Polylang is not activated on site

### ISSUE THREAD

**Issue by ronilaukkarinen** [digitoimistodude/air-helper#57]
Sometimes we have scenarios where the website doesn't use Polylang but we still use translatable strings via [inc/includes/localization.php](https://github.com/digitoimistodude/air-light/blob/2d16fec898153a6ee6d699c6a605a3acc69d1853/inc/includes/localization.php). It would be nice to have a way to update localizations when needed without having to hardcode them into the file.

**Comment by timiwahalahti** [comment]
Added in https://github.com/digitoimistodude/air-helper/commit/6e2ea067befd5cd174b3235192edb3cb387dd5da
