### ISSUE TITLE
Broken Admin-Menu

### ISSUE THREAD

**Issue by samex** [digitoimistodude/air-helper#65]
After installing the plugin, the menu in admin area is broken. The section "Design" dissapears. 

Plugin Version: 2.18.0
Wordpress: 6.1.1

**Comment by timiwahalahti** [comment]
Hello! That is intended behaviour since, typically, in our projects, there's no need to visit the "Design" or "Theme" part of the dashboard. See https://github.com/digitoimistodude/air-helper/blob/master/inc/admin/access.php#L114-L122
